version: '3'
services:

  app_ui:
    build:
      context: ../app_ui/
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ../box:/app_ui/box
      - ../app_ui:/app_ui
    restart: on-failure