version: '3'
services:
  scan_anomaly:
    build:
      context: ../scan_anomaly/
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    volumes:
      - ../box:/scan_anomaly/box
      - ../scan_anomaly:/scan_anomaly
    deploy:
      resources:
        limits:
          cpus: '8' # Limit to half a CPU core
          memory: 4096M # Limit to 256 megabytes of memory
    restart: on-failure
    
  app_ui:
    build:
      context: ../app_ui/
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ../box:/app_ui/box
      - ../app_ui:/app_ui
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limit to half a CPU core
          memory: 512M # Limit to 256 megabytes of memory
    restart: on-failure
