version: '3'
services:
  defect_classify:
    build:
      context: ../defect_classify/
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ../box:/defect_classify/box
      - ../defect_classify:/defect_classify
    deploy:
      resources:
        limits:
          cpus: '1' # Limit to half a CPU core
          memory: 512M # Limit to 256 megabytes of memory
    restart: on-failure

services:
  waveform_probe:
    build:
      context: ../waveform_probe/
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ../box:/waveform_probe/box
      - ../waveform_probe:/waveform_probe
    deploy:
      resources:
        limits:
          cpus: '1' # Limit to half a CPU core
          memory: 512M # Limit to 256 megabytes of memory
    restart: on-failure


  app_ui:
    build:
      context: ../app_ui/
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ../box:/app_ui/box
      - ../app_ui:/app_ui
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limit to half a CPU core
          memory: 512M # Limit to 256 megabytes of memory
    restart: on-failure